name: Build

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup node
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'
          cache: gradle

      - name: Setup gradlew
        run: |
          ./gradlew genEclipseRuns;

      - name: Write version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export TAG=$(echo "${{ github.ref }}"|cut -d/ -f3);
          export MOD_VERSION=$(echo $TAG|cut -d- -f1);
          export MC_VERSION=$(echo $TAG|cut -d- -f2);
          echo "Build: $MOD_VERSION-$MC_VERSION";
          sed -i s/\"version\":\ \"[0-9]\.X\.XDEV/\"version\":\ \"$MOD_VERSION/ src/main/resources/mcmod.info;
          sed -i s/modversion\ =\ \"[0-9]\.X\.XDEV/modversion\ =\ \"$MOD_VERSION/ build.gradle;
          sed -i s/VERSION\ =\ \"[0-9]\.X\.XDEV/VERSION\ =\ \"$MOD_VERSION/ src/main/java/com/gollum/core/ModGollumCoreLib.java;
          
      - name: Build
        run: |
          ./gradlew build;
      
      - name: Publish DEV
        if: startsWith(github.ref, 'refs/heads/')
        uses: nogsantos/scp-deploy@master
        with:
          src: ./build/libs/*
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR_DEV }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
      
      - name: Publish PROD
        if: startsWith(github.ref, 'refs/tags/')
        uses: nogsantos/scp-deploy@master
        with:
          src: ./build/libs/*
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR_PROD }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
      
      - name: Notify discord success
        uses: th0th/notify-discord@v0.4.1
        if: ${{ success() }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_JOB_NAME: "Build and deploy"
          GITHUB_JOB_STATUS: 'success'

      - name: Notify discord failure
        uses: th0th/notify-discord@v0.4.1
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_JOB_NAME: "Build and deploy"
          GITHUB_JOB_STATUS: 'failure'